version: 2
jobs:
  build:
    docker:
      - image: cypress/browsers:node-16.18.1-chrome-110.0.5481.96-1-ff-109.0-edge-110.0.1587.41-1
        environment:
          TERM: xterm
    working_directory: ~/root

    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
            - yarn-packages

      - run:
          name: Environment
          command: |
            node --version
            npm --version
            yarn --version
      - run:
          name: Installing dependencies
          command: yarn
      - save_cache:
          name: Saving package cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Running tests
          command: yarn test
